// This file was generated by dart_openapi_model_gen
class ClubType {
  static const modelName = "club_type";

  final String id;
  final String createdAt;
  final String? type;

  ClubType({required  this.id, required  this.createdAt,  this.type, });

  ClubType copyWith({
    String? id,
    String? createdAt,
    String? type,
  }) => ClubType(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        type: type ?? this.type, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'type': type,
  };

  factory ClubType.fromJson(Map<String, dynamic> json) => ClubType(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        type: json['type'] as String?,
  );
}
