// This file was generated by dart_openapi_model_gen
class Club {
  static const modelName = "club";

  final String id;
  final String createdAt;
  final String openingTime;
  final String closingTime;
  final String description;
  final double femalePrice;
  final double menPrice;
  final List<String>? subImages;
  final String name;
  final String? image;
  final double lat;
  final double lng;
  final String? locationAddress;
  final int femaleDrinkTicket;
  final int maleDrinkTicket;
  final String? rulesAndRegulation;
  final String? updatedAt;
  final List<String>? genre;
  final List<String>? workingDay;
  final int guestlist;
  final double guestlistDiscount;
  final List<String>? clubType;
  final String? email;

  Club({required  this.id, required  this.createdAt, required  this.openingTime, required  this.closingTime, required  this.description, required  this.femalePrice, required  this.menPrice,  this.subImages, required  this.name,  this.image, required  this.lat, required  this.lng,  this.locationAddress, required  this.femaleDrinkTicket, required  this.maleDrinkTicket,  this.rulesAndRegulation,  this.updatedAt,  this.genre,  this.workingDay, required  this.guestlist, required  this.guestlistDiscount,  this.clubType,  this.email, });

  Club copyWith({
    String? id,
    String? createdAt,
    String? openingTime,
    String? closingTime,
    String? description,
    double? femalePrice,
    double? menPrice,
    List<String>? subImages,
    String? name,
    String? image,
    double? lat,
    double? lng,
    String? locationAddress,
    int? femaleDrinkTicket,
    int? maleDrinkTicket,
    String? rulesAndRegulation,
    String? updatedAt,
    List<String>? genre,
    List<String>? workingDay,
    int? guestlist,
    double? guestlistDiscount,
    List<String>? clubType,
    String? email,
  }) => Club(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        openingTime: openingTime ?? this.openingTime, 
        closingTime: closingTime ?? this.closingTime, 
        description: description ?? this.description, 
        femalePrice: femalePrice ?? this.femalePrice, 
        menPrice: menPrice ?? this.menPrice, 
        subImages: subImages ?? this.subImages, 
        name: name ?? this.name, 
        image: image ?? this.image, 
        lat: lat ?? this.lat, 
        lng: lng ?? this.lng, 
        locationAddress: locationAddress ?? this.locationAddress, 
        femaleDrinkTicket: femaleDrinkTicket ?? this.femaleDrinkTicket, 
        maleDrinkTicket: maleDrinkTicket ?? this.maleDrinkTicket, 
        rulesAndRegulation: rulesAndRegulation ?? this.rulesAndRegulation, 
        updatedAt: updatedAt ?? this.updatedAt, 
        genre: genre ?? this.genre, 
        workingDay: workingDay ?? this.workingDay, 
        guestlist: guestlist ?? this.guestlist, 
        guestlistDiscount: guestlistDiscount ?? this.guestlistDiscount, 
        clubType: clubType ?? this.clubType, 
        email: email ?? this.email, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'opening_time': openingTime,
        'closing_time': closingTime,
        'description': description,
        'female_price': femalePrice,
        'men_price': menPrice,
        'sub_images': subImages,
        'name': name,
        'image': image,
        'lat': lat,
        'lng': lng,
        'location_address': locationAddress,
        'female_drink_ticket': femaleDrinkTicket,
        'male_drink_ticket': maleDrinkTicket,
        'rules_and_regulation': rulesAndRegulation,
        'updated_at': updatedAt,
        'genre': genre,
        'working_day': workingDay,
        'guestlist': guestlist,
        'guestlist_discount': guestlistDiscount,
        'club_type': clubType,
        'email': email,
  };

  factory Club.fromJson(Map<String, dynamic> json) => Club(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        openingTime: json['opening_time'] as String,
        closingTime: json['closing_time'] as String,
        description: json['description'] as String,
        femalePrice: json['female_price'].toDouble(),
        menPrice: json['men_price'].toDouble(),
        subImages: json['sub_images']?.cast<String>(),
        name: json['name'] as String,
        image: json['image'] as String?,
        lat: json['lat'].toDouble(),
        lng: json['lng'].toDouble(),
        locationAddress: json['location_address'] as String?,
        femaleDrinkTicket: json['female_drink_ticket'] as int,
        maleDrinkTicket: json['male_drink_ticket'] as int,
        rulesAndRegulation: json['rules_and_regulation'] as String?,
        updatedAt: json['updated_at'] as String?,
        genre: json['genre']?.cast<String>(),
        workingDay: json['working_day']?.cast<String>(),
        guestlist: json['guestlist'] as int,
        guestlistDiscount: json['guestlist_discount'].toDouble(),
        clubType: json['club_type']?.cast<String>(),
        email: json['email'] as String?,
  );
}
