// This file was generated by dart_openapi_model_gen
import './staff.dart';


class ClubStaff {
  static const modelName = "club_staff";

  final String id;
  final String createdAt;
  final String? clubId;
  final Staff? role;
  final String? name;
  final String? email;

  ClubStaff({required  this.id, required  this.createdAt,  this.clubId,  this.role,  this.name,  this.email, });

  ClubStaff copyWith({
    String? id,
    String? createdAt,
    String? clubId,
    Staff? role,
    String? name,
    String? email,
  }) => ClubStaff(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        clubId: clubId ?? this.clubId, 
        role: role ?? this.role, 
        name: name ?? this.name, 
        email: email ?? this.email, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'club_id': clubId,
        'role': role?.name,
        'name': name,
        'email': email,
  };

  factory ClubStaff.fromJson(Map<String, dynamic> json) => ClubStaff(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        clubId: json['club_id'] as String?,
        role: Staff.values.where((e) => e.name == json['role']).firstOrNull,
        name: json['name'] as String?,
        email: json['email'] as String?,
  );
}
