// This file was generated by dart_openapi_model_gen and extended manually
class Club {
  static const modelName = "club";

  final String id;
  final String createdAt;
  final String openingTime;
  final String closingTime;
  final String description;
  final double femalePrice;
  final double menPrice;
  final List<String>? subImages;
  final String name;
  final String? image;
  final double lat;
  final double lng;
  final String? locationAddress;
  final int femaleDrinkTicket;
  final int maleDrinkTicket;
  final String? rulesAndRegulation;
  final String? updatedAt;
  final List<String>? genre;
  final List<String>? workingDay;
  final int guestlist;
  final double guestlistDiscount;
  final List<String>? clubType;
  final String? email;

  // Venue-map fields (populated for all clubs; partner_club=true for existing partner clubs)
  final bool partnerClub;
  final String? venueType; // 'bar' | 'club'
  final String? area;
  final double? rating;
  final String? googleMapsUrl;
  final List<String>? musicGenres;
  final String? crowdType;
  final String? dressCode;
  final String? ageLimit;
  // Places API sync fields
  final bool isActive;
  final String? placeId;
  final String? lastSyncedAt;

  Club({
    required this.id,
    required this.createdAt,
    required this.openingTime,
    required this.closingTime,
    required this.description,
    required this.femalePrice,
    required this.menPrice,
    this.subImages,
    required this.name,
    this.image,
    required this.lat,
    required this.lng,
    this.locationAddress,
    required this.femaleDrinkTicket,
    required this.maleDrinkTicket,
    this.rulesAndRegulation,
    this.updatedAt,
    this.genre,
    this.workingDay,
    required this.guestlist,
    required this.guestlistDiscount,
    this.clubType,
    this.email,
    this.partnerClub = false,
    this.venueType,
    this.area,
    this.rating,
    this.googleMapsUrl,
    this.musicGenres,
    this.crowdType,
    this.dressCode,
    this.ageLimit,
    this.isActive = true,
    this.placeId,
    this.lastSyncedAt,
  });

  Club copyWith({
    String? id,
    String? createdAt,
    String? openingTime,
    String? closingTime,
    String? description,
    double? femalePrice,
    double? menPrice,
    List<String>? subImages,
    String? name,
    String? image,
    double? lat,
    double? lng,
    String? locationAddress,
    int? femaleDrinkTicket,
    int? maleDrinkTicket,
    String? rulesAndRegulation,
    String? updatedAt,
    List<String>? genre,
    List<String>? workingDay,
    int? guestlist,
    double? guestlistDiscount,
    List<String>? clubType,
    String? email,
    bool? partnerClub,
    String? venueType,
    String? area,
    double? rating,
    String? googleMapsUrl,
    List<String>? musicGenres,
    String? crowdType,
    String? dressCode,
    String? ageLimit,
    bool? isActive,
    String? placeId,
    String? lastSyncedAt,
  }) => Club(
        id: id ?? this.id,
        createdAt: createdAt ?? this.createdAt,
        openingTime: openingTime ?? this.openingTime,
        closingTime: closingTime ?? this.closingTime,
        description: description ?? this.description,
        femalePrice: femalePrice ?? this.femalePrice,
        menPrice: menPrice ?? this.menPrice,
        subImages: subImages ?? this.subImages,
        name: name ?? this.name,
        image: image ?? this.image,
        lat: lat ?? this.lat,
        lng: lng ?? this.lng,
        locationAddress: locationAddress ?? this.locationAddress,
        femaleDrinkTicket: femaleDrinkTicket ?? this.femaleDrinkTicket,
        maleDrinkTicket: maleDrinkTicket ?? this.maleDrinkTicket,
        rulesAndRegulation: rulesAndRegulation ?? this.rulesAndRegulation,
        updatedAt: updatedAt ?? this.updatedAt,
        genre: genre ?? this.genre,
        workingDay: workingDay ?? this.workingDay,
        guestlist: guestlist ?? this.guestlist,
        guestlistDiscount: guestlistDiscount ?? this.guestlistDiscount,
        clubType: clubType ?? this.clubType,
        email: email ?? this.email,
        partnerClub: partnerClub ?? this.partnerClub,
        venueType: venueType ?? this.venueType,
        area: area ?? this.area,
        rating: rating ?? this.rating,
        googleMapsUrl: googleMapsUrl ?? this.googleMapsUrl,
        musicGenres: musicGenres ?? this.musicGenres,
        crowdType: crowdType ?? this.crowdType,
        dressCode: dressCode ?? this.dressCode,
        ageLimit: ageLimit ?? this.ageLimit,
        isActive: isActive ?? this.isActive,
        placeId: placeId ?? this.placeId,
        lastSyncedAt: lastSyncedAt ?? this.lastSyncedAt,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'opening_time': openingTime,
        'closing_time': closingTime,
        'description': description,
        'female_price': femalePrice,
        'men_price': menPrice,
        'sub_images': subImages,
        'name': name,
        'image': image,
        'lat': lat,
        'lng': lng,
        'location_address': locationAddress,
        'female_drink_ticket': femaleDrinkTicket,
        'male_drink_ticket': maleDrinkTicket,
        'rules_and_regulation': rulesAndRegulation,
        'updated_at': updatedAt,
        'genre': genre,
        'working_day': workingDay,
        'guestlist': guestlist,
        'guestlist_discount': guestlistDiscount,
        'club_type': clubType,
        'email': email,
        'partner_club': partnerClub,
        'venue_type': venueType,
        'area': area,
        'rating': rating,
        'google_maps_url': googleMapsUrl,
        'music_genres': musicGenres,
        'crowd_type': crowdType,
        'dress_code': dressCode,
        'age_limit': ageLimit,
        'is_active': isActive,
        'place_id': placeId,
        'last_synced_at': lastSyncedAt,
      };

  factory Club.fromJson(Map<String, dynamic> json) => Club(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        openingTime: json['opening_time'] as String? ?? '',
        closingTime: json['closing_time'] as String? ?? '',
        description: json['description'] as String? ?? '',
        femalePrice: (json['female_price'] as num?)?.toDouble() ?? 0.0,
        menPrice: (json['men_price'] as num?)?.toDouble() ?? 0.0,
        subImages: json['sub_images']?.cast<String>(),
        name: json['name'] as String,
        image: json['image'] as String?,
        lat: (json['lat'] as num).toDouble(),
        lng: (json['lng'] as num).toDouble(),
        locationAddress: json['location_address'] as String?,
        femaleDrinkTicket: json['female_drink_ticket'] as int? ?? 0,
        maleDrinkTicket: json['male_drink_ticket'] as int? ?? 0,
        rulesAndRegulation: json['rules_and_regulation'] as String?,
        updatedAt: json['updated_at'] as String?,
        genre: json['genre']?.cast<String>(),
        workingDay: json['working_day']?.cast<String>(),
        guestlist: json['guestlist'] as int? ?? 0,
        guestlistDiscount: (json['guestlist_discount'] as num?)?.toDouble() ?? 0.0,
        clubType: json['club_type']?.cast<String>(),
        email: json['email'] as String?,
        partnerClub: json['partner_club'] as bool? ?? false,
        venueType: json['venue_type'] as String?,
        area: json['area'] as String?,
        rating: (json['rating'] as num?)?.toDouble(),
        googleMapsUrl: json['google_maps_url'] as String?,
        musicGenres: (json['music_genres'] as List?)?.cast<String>(),
        crowdType: json['crowd_type'] as String?,
        dressCode: json['dress_code'] as String?,
        ageLimit: json['age_limit'] as String?,
        isActive: json['is_active'] as bool? ?? true,
        placeId: json['place_id'] as String?,
        lastSyncedAt: json['last_synced_at'] as String?,
      );
}
