// This file was generated by dart_openapi_model_gen
class DrinkTicket {
  static const modelName = "drink_ticket";

  final String id;
  final String createdAt;
  final String? userId;
  final String? qrCode;
  final String expiryDate;
  final String eventId;
  final String? senderId;
  final String? usedTime;
  final String? clubId;
  final bool isAssigned;
  final String? eventTicketId;
  final String? eventName;
  final String? image;
  final bool promoterTicket;
  final String? redeemerName;

  DrinkTicket({required  this.id, required  this.createdAt,  this.userId,  this.qrCode, required  this.expiryDate, required  this.eventId,  this.senderId,  this.usedTime,  this.clubId, required  this.isAssigned,  this.eventTicketId,  this.eventName,  this.image, required  this.promoterTicket,  this.redeemerName, });

  DrinkTicket copyWith({
    String? id,
    String? createdAt,
    String? userId,
    String? qrCode,
    String? expiryDate,
    String? eventId,
    String? senderId,
    String? usedTime,
    String? clubId,
    bool? isAssigned,
    String? eventTicketId,
    String? eventName,
    String? image,
    bool? promoterTicket,
    String? redeemerName,
  }) => DrinkTicket(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        userId: userId ?? this.userId, 
        qrCode: qrCode ?? this.qrCode, 
        expiryDate: expiryDate ?? this.expiryDate, 
        eventId: eventId ?? this.eventId, 
        senderId: senderId ?? this.senderId, 
        usedTime: usedTime ?? this.usedTime, 
        clubId: clubId ?? this.clubId, 
        isAssigned: isAssigned ?? this.isAssigned, 
        eventTicketId: eventTicketId ?? this.eventTicketId, 
        eventName: eventName ?? this.eventName, 
        image: image ?? this.image, 
        promoterTicket: promoterTicket ?? this.promoterTicket, 
        redeemerName: redeemerName ?? this.redeemerName, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'user_id': userId,
        'qr_code': qrCode,
        'expiry_date': expiryDate,
        'event_id': eventId,
        'sender_id': senderId,
        'used_time': usedTime,
        'club_id': clubId,
        'is_assigned': isAssigned,
        'event_ticket_id': eventTicketId,
        'event_name': eventName,
        'image': image,
        'promoter_ticket': promoterTicket,
        'redeemer_name': redeemerName,
  };

  factory DrinkTicket.fromJson(Map<String, dynamic> json) => DrinkTicket(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        userId: json['user_id'] as String?,
        qrCode: json['qr_code'] as String?,
        expiryDate: json['expiry_date'] as String,
        eventId: json['event_id'] as String,
        senderId: json['sender_id'] as String?,
        usedTime: json['used_time'] as String?,
        clubId: json['club_id'] as String?,
        isAssigned: json['is_assigned'] as bool,
        eventTicketId: json['event_ticket_id'] as String?,
        eventName: json['event_name'] as String?,
        image: json['image'] as String?,
        promoterTicket: json['promoter_ticket'] as bool,
        redeemerName: json['redeemer_name'] as String?,
  );
}
