// This file was generated by dart_openapi_model_gen
class EmailTemplate {
  static const modelName = "email_template";

  final int id;
  final String createdAt;
  final String? name;
  final String? subjectLine;
  final String? template;
  final String? layoutId;

  EmailTemplate({required  this.id, required  this.createdAt,  this.name,  this.subjectLine,  this.template,  this.layoutId, });

  EmailTemplate copyWith({
    int? id,
    String? createdAt,
    String? name,
    String? subjectLine,
    String? template,
    String? layoutId,
  }) => EmailTemplate(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        name: name ?? this.name, 
        subjectLine: subjectLine ?? this.subjectLine, 
        template: template ?? this.template, 
        layoutId: layoutId ?? this.layoutId, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'name': name,
        'subject_line': subjectLine,
        'template': template,
        'layout_id': layoutId,
  };

  factory EmailTemplate.fromJson(Map<String, dynamic> json) => EmailTemplate(
        id: json['id'] as int,
        createdAt: json['created_at'] as String,
        name: json['name'] as String?,
        subjectLine: json['subject_line'] as String?,
        template: json['template'] as String?,
        layoutId: json['layout_id'] as String?,
  );
}
