// This file was generated by dart_openapi_model_gen
class Event {
  static const modelName = "event";

  final String id;
  final String createdAt;
  final String name;
  final String image;
  final String description;
  final double? femalePrice;
  final String startDate;
  final String endDate;
  final List<String>? subImages;
  final int pending;
  final int checkedIn;
  final String clubId;
  final double malePrice;
  final bool isRecurring;
  final String? locationAdress;
  final int freeFemaleDrinkTicket;
  final int freeMaleDrinkTicket;
  final List<String> category;
  final int guestlist;
  final int earlybird;
  final int earlybirdDiscount;
  final int registeredGuestlist;
  final String? clubName;
  final bool payAtTheDoorAvailable;
  final bool? isServiceTaxIncluded;

  Event({required  this.id, required  this.createdAt, required  this.name, required  this.image, required  this.description,  this.femalePrice, required  this.startDate, required  this.endDate,  this.subImages, required  this.pending, required  this.checkedIn, required  this.clubId, required  this.malePrice, required  this.isRecurring,  this.locationAdress, required  this.freeFemaleDrinkTicket, required  this.freeMaleDrinkTicket, required  this.category, required  this.guestlist, required  this.earlybird, required  this.earlybirdDiscount, required  this.registeredGuestlist,  this.clubName, required  this.payAtTheDoorAvailable,  this.isServiceTaxIncluded, });

  Event copyWith({
    String? id,
    String? createdAt,
    String? name,
    String? image,
    String? description,
    double? femalePrice,
    String? startDate,
    String? endDate,
    List<String>? subImages,
    int? pending,
    int? checkedIn,
    String? clubId,
    double? malePrice,
    bool? isRecurring,
    String? locationAdress,
    int? freeFemaleDrinkTicket,
    int? freeMaleDrinkTicket,
    List<String>? category,
    int? guestlist,
    int? earlybird,
    int? earlybirdDiscount,
    int? registeredGuestlist,
    String? clubName,
    bool? payAtTheDoorAvailable,
    bool? isServiceTaxIncluded,
  }) => Event(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        name: name ?? this.name, 
        image: image ?? this.image, 
        description: description ?? this.description, 
        femalePrice: femalePrice ?? this.femalePrice, 
        startDate: startDate ?? this.startDate, 
        endDate: endDate ?? this.endDate, 
        subImages: subImages ?? this.subImages, 
        pending: pending ?? this.pending, 
        checkedIn: checkedIn ?? this.checkedIn, 
        clubId: clubId ?? this.clubId, 
        malePrice: malePrice ?? this.malePrice, 
        isRecurring: isRecurring ?? this.isRecurring, 
        locationAdress: locationAdress ?? this.locationAdress, 
        freeFemaleDrinkTicket: freeFemaleDrinkTicket ?? this.freeFemaleDrinkTicket, 
        freeMaleDrinkTicket: freeMaleDrinkTicket ?? this.freeMaleDrinkTicket, 
        category: category ?? this.category, 
        guestlist: guestlist ?? this.guestlist, 
        earlybird: earlybird ?? this.earlybird, 
        earlybirdDiscount: earlybirdDiscount ?? this.earlybirdDiscount, 
        registeredGuestlist: registeredGuestlist ?? this.registeredGuestlist, 
        clubName: clubName ?? this.clubName, 
        payAtTheDoorAvailable: payAtTheDoorAvailable ?? this.payAtTheDoorAvailable, 
        isServiceTaxIncluded: isServiceTaxIncluded ?? this.isServiceTaxIncluded, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'name': name,
        'image': image,
        'description': description,
        'female_price': femalePrice,
        'start_date': startDate,
        'end_date': endDate,
        'sub_images': subImages,
        'pending': pending,
        'checked_in': checkedIn,
        'club_id': clubId,
        'male_price': malePrice,
        'is_recurring': isRecurring,
        'location_adress': locationAdress,
        'free_female_drink_ticket': freeFemaleDrinkTicket,
        'free_male_drink_ticket': freeMaleDrinkTicket,
        'category': category,
        'guestlist': guestlist,
        'earlybird': earlybird,
        'earlybird_discount': earlybirdDiscount,
        'registered_guestlist': registeredGuestlist,
        'club_name': clubName,
        'pay_at_the_door_available': payAtTheDoorAvailable,
        'is_service_tax_included': isServiceTaxIncluded,
  };

  factory Event.fromJson(Map<String, dynamic> json) => Event(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        name: json['name'] as String,
        image: json['image'] as String,
        description: json['description'] as String,
        femalePrice: json['female_price']?.toDouble(),
        startDate: json['start_date'] as String,
        endDate: json['end_date'] as String,
        subImages: json['sub_images']?.cast<String>(),
        pending: json['pending'] as int,
        checkedIn: json['checked_in'] as int,
        clubId: json['club_id'] as String,
        malePrice: json['male_price'].toDouble(),
        isRecurring: json['is_recurring'] as bool,
        locationAdress: json['location_adress'] as String?,
        freeFemaleDrinkTicket: json['free_female_drink_ticket'] as int,
        freeMaleDrinkTicket: json['free_male_drink_ticket'] as int,
        category: json['category'].cast<String>(),
        guestlist: json['guestlist'] as int,
        earlybird: json['earlybird'] as int,
        earlybirdDiscount: json['earlybird_discount'] as int,
        registeredGuestlist: json['registered_guestlist'] as int,
        clubName: json['club_name'] as String?,
        payAtTheDoorAvailable: json['pay_at_the_door_available'] as bool,
        isServiceTaxIncluded: json['is_service_tax_included'] as bool?,
  );
}
