// This file was generated by dart_openapi_model_gen
class EventTicket {
  static const modelName = "event_ticket";

  final String id;
  final String createdAt;
  final String? clubId;
  final String qrCode;
  final String expiryDate;
  final String eventId;
  final String userId;
  final String? eventName;
  final double price;
  final String? senderId;
  final bool checkedIn;
  final String? gender;
  final bool isGuestlist;
  final bool isPayAtDoor;
  final String? clubName;
  final String? attendeeName;
  final String? eventDate;
  final String? image;

  EventTicket({required  this.id, required  this.createdAt,  this.clubId, required  this.qrCode, required  this.expiryDate, required  this.eventId, required  this.userId,  this.eventName, required  this.price,  this.senderId, required  this.checkedIn,  this.gender, required  this.isGuestlist, required  this.isPayAtDoor,  this.clubName,  this.attendeeName,  this.eventDate,  this.image, });

  EventTicket copyWith({
    String? id,
    String? createdAt,
    String? clubId,
    String? qrCode,
    String? expiryDate,
    String? eventId,
    String? userId,
    String? eventName,
    double? price,
    String? senderId,
    bool? checkedIn,
    String? gender,
    bool? isGuestlist,
    bool? isPayAtDoor,
    String? clubName,
    String? attendeeName,
    String? eventDate,
    String? image,
  }) => EventTicket(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        clubId: clubId ?? this.clubId, 
        qrCode: qrCode ?? this.qrCode, 
        expiryDate: expiryDate ?? this.expiryDate, 
        eventId: eventId ?? this.eventId, 
        userId: userId ?? this.userId, 
        eventName: eventName ?? this.eventName, 
        price: price ?? this.price, 
        senderId: senderId ?? this.senderId, 
        checkedIn: checkedIn ?? this.checkedIn, 
        gender: gender ?? this.gender, 
        isGuestlist: isGuestlist ?? this.isGuestlist, 
        isPayAtDoor: isPayAtDoor ?? this.isPayAtDoor, 
        clubName: clubName ?? this.clubName, 
        attendeeName: attendeeName ?? this.attendeeName, 
        eventDate: eventDate ?? this.eventDate, 
        image: image ?? this.image, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'club_id': clubId,
        'qr_code': qrCode,
        'expiry_date': expiryDate,
        'event_id': eventId,
        'user_id': userId,
        'event_name': eventName,
        'price': price,
        'sender_id': senderId,
        'checked_in': checkedIn,
        'gender': gender,
        'is_guestlist': isGuestlist,
        'is_pay_at_door': isPayAtDoor,
        'club_name': clubName,
        'attendee_name': attendeeName,
        'event_date': eventDate,
        'image': image,
  };

  factory EventTicket.fromJson(Map<String, dynamic> json) => EventTicket(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        clubId: json['club_id'] as String?,
        qrCode: json['qr_code'] as String,
        expiryDate: json['expiry_date'] as String,
        eventId: json['event_id'] as String,
        userId: json['user_id'] as String,
        eventName: json['event_name'] as String?,
        price: json['price'].toDouble(),
        senderId: json['sender_id'] as String?,
        checkedIn: json['checked_in'] as bool,
        gender: json['gender'] as String?,
        isGuestlist: json['is_guestlist'] as bool,
        isPayAtDoor: json['is_pay_at_door'] as bool,
        clubName: json['club_name'] as String?,
        attendeeName: json['attendee_name'] as String?,
        eventDate: json['event_date'] as String?,
        image: json['image'] as String?,
  );
}
