// This file was generated by dart_openapi_model_gen
class EventCategory {
  static const modelName = "event_category";

  final String createdAt;
  final String? category;
  final String id;
  final int order;
  final String? image;

  EventCategory({required  this.createdAt,  this.category, required  this.id, required  this.order,  this.image, });

  EventCategory copyWith({
    String? createdAt,
    String? category,
    String? id,
    int? order,
    String? image,
  }) => EventCategory(
        createdAt: createdAt ?? this.createdAt, 
        category: category ?? this.category, 
        id: id ?? this.id, 
        order: order ?? this.order, 
        image: image ?? this.image, 
  );

  Map<String, dynamic> toJson() => {
        'created_at': createdAt,
        'category': category,
        'id': id,
        'order': order,
        'image': image,
  };

  factory EventCategory.fromJson(Map<String, dynamic> json) => EventCategory(
        createdAt: json['created_at'] as String,
        category: json['category'] as String?,
        id: json['id'] as String,
        order: json['order'] as int,
        image: json['image'] as String?,
  );
}
