// This file was generated by dart_openapi_model_gen
class InAppNotification {
  static const modelName = "in_app_notification";

  final String id;
  final String createdAt;
  final String? title;
  final String? content;

  InAppNotification({required  this.id, required  this.createdAt,  this.title,  this.content, });

  InAppNotification copyWith({
    String? id,
    String? createdAt,
    String? title,
    String? content,
  }) => InAppNotification(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        title: title ?? this.title, 
        content: content ?? this.content, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'title': title,
        'content': content,
  };

  factory InAppNotification.fromJson(Map<String, dynamic> json) => InAppNotification(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        title: json['title'] as String?,
        content: json['content'] as String?,
  );
}
