// This file was generated by dart_openapi_model_gen
class OrganiserProfile {
  static const modelName = "organiser_profile";

  final String id;
  final String createdAt;
  final String name;
  final String birthdate;
  final String? description;
  final String? image;
  final String? updatedAt;

  OrganiserProfile({required  this.id, required  this.createdAt, required  this.name, required  this.birthdate,  this.description,  this.image,  this.updatedAt, });

  OrganiserProfile copyWith({
    String? id,
    String? createdAt,
    String? name,
    String? birthdate,
    String? description,
    String? image,
    String? updatedAt,
  }) => OrganiserProfile(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        name: name ?? this.name, 
        birthdate: birthdate ?? this.birthdate, 
        description: description ?? this.description, 
        image: image ?? this.image, 
        updatedAt: updatedAt ?? this.updatedAt, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'name': name,
        'birthdate': birthdate,
        'description': description,
        'image': image,
        'updated_at': updatedAt,
  };

  factory OrganiserProfile.fromJson(Map<String, dynamic> json) => OrganiserProfile(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        name: json['name'] as String,
        birthdate: json['birthdate'] as String,
        description: json['description'] as String?,
        image: json['image'] as String?,
        updatedAt: json['updated_at'] as String?,
  );
}
