// This file was generated by dart_openapi_model_gen
class UserWallet {
  static const modelName = "user_wallet";

  final String id;
  final String createdAt;
  final int? credits;
  final String? updatedAt;

  UserWallet({required  this.id, required  this.createdAt,  this.credits,  this.updatedAt, });

  UserWallet copyWith({
    String? id,
    String? createdAt,
    int? credits,
    String? updatedAt,
  }) => UserWallet(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        credits: credits ?? this.credits, 
        updatedAt: updatedAt ?? this.updatedAt, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'credits': credits,
        'updated_at': updatedAt,
  };

  factory UserWallet.fromJson(Map<String, dynamic> json) => UserWallet(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        credits: json['credits'] as int?,
        updatedAt: json['updated_at'] as String?,
  );
}
