// This file was generated by dart_openapi_model_gen
import './gender.dart';


class UserProfile {
  static const modelName = "user_profile";

  final String id;
  final String createdAt;
  final String? name;
  final String? contactEmail;
  final String? stripeCustomerId;
  final String? username;
  final String? image;
  final Gender gender;

  UserProfile({required  this.id, required  this.createdAt,  this.name,  this.contactEmail,  this.stripeCustomerId,  this.username,  this.image, required  this.gender, });

  UserProfile copyWith({
    String? id,
    String? createdAt,
    String? name,
    String? contactEmail,
    String? stripeCustomerId,
    String? username,
    String? image,
    Gender? gender,
  }) => UserProfile(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        name: name ?? this.name, 
        contactEmail: contactEmail ?? this.contactEmail, 
        stripeCustomerId: stripeCustomerId ?? this.stripeCustomerId, 
        username: username ?? this.username, 
        image: image ?? this.image, 
        gender: gender ?? this.gender, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'name': name,
        'contact_email': contactEmail,
        'stripe_customer_id': stripeCustomerId,
        'username': username,
        'image': image,
        'gender': gender.name,
  };

  factory UserProfile.fromJson(Map<String, dynamic> json) => UserProfile(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        name: json['name'] as String?,
        contactEmail: json['contact_email'] as String?,
        stripeCustomerId: json['stripe_customer_id'] as String?,
        username: json['username'] as String?,
        image: json['image'] as String?,
        gender: Gender.values.where((e) => e.name == json['gender']).first,
  );
}
