// This file was generated by dart_openapi_model_gen
class UserWalletEvent {
  static const modelName = "user_wallet_event";

  final String id;
  final String createdAt;
  final String reason;
  final int balanceChange;
  final String? userId;
  final dynamic payload;

  UserWalletEvent({required  this.id, required  this.createdAt, required  this.reason, required  this.balanceChange,  this.userId,  this.payload, });

  UserWalletEvent copyWith({
    String? id,
    String? createdAt,
    String? reason,
    int? balanceChange,
    String? userId,
    dynamic payload,
  }) => UserWalletEvent(
        id: id ?? this.id, 
        createdAt: createdAt ?? this.createdAt, 
        reason: reason ?? this.reason, 
        balanceChange: balanceChange ?? this.balanceChange, 
        userId: userId ?? this.userId, 
        payload: payload ?? this.payload, 
  );

  Map<String, dynamic> toJson() => {
        'id': id,
        'created_at': createdAt,
        'reason': reason,
        'balance_change': balanceChange,
        'user_id': userId,
        'payload': payload,
  };

  factory UserWalletEvent.fromJson(Map<String, dynamic> json) => UserWalletEvent(
        id: json['id'] as String,
        createdAt: json['created_at'] as String,
        reason: json['reason'] as String,
        balanceChange: json['balance_change'] as int,
        userId: json['user_id'] as String?,
        payload: json['payload'] as dynamic,
  );
}
